### ISSUE TITLE
not working properly 

### ISSUE THREAD

**Issue by ahmedkhan** [TahaAnwar/opensource#1]
no line can be drawn when i move a pen

**Comment by TahaAnwar** [comment]
> no line can be drawn when i move a pen

you have two options either use the same shade of highlighter that i used or either get the hsv range of range of the pen that you have. and only try this script if you some experience with opencv otherwise you will have a headache.

**Comment by ahmedkhan** [comment]
I think you used a yellow high lighter? can you plz tell me what can I do if I want to use a black marker

**Comment by ahmedkhan** [comment]
If i want to clear a screen what should i do
