### ISSUE TITLE
Error:File not found

### ISSUE THREAD

**Issue by nikhilabhi** [TahaAnwar/opensource#2]
**ERROR:**
  **File "/home/qtpi/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 422, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'handextt.npy'**

Can you help me out in sloving this problem.

We tried to creating **handextt.npy** file in the location but it didn't work.

**Comment by TahaAnwar** [comment]
this file is added now
